Updates for Auth2 compatibility
msneddon/KBaseReport pull request #4
Opened 2017-03-09 20:16 UTC by msneddon

2017-03-09 20:33 UTC, rsutormin requested changes

2017-03-09 20:33 UTC, rsutormin commented on lib/KBaseReport/KBaseReportImpl.pm.bak-2017-03-06-15-59-41
> +package KBaseReport::KBaseReportImpl;
Is there any reason for committing this file.

2017-03-09 20:33 UTC, rsutormin commented on test/KBaseReport_server_test.pl
>  my $auth_token = Bio::KBase::AuthToken->new(token => $token, ignore_authrc => 1);
I think this line can not work properly. Why don't you refactor token validation similar to https://github.com/kbase/kb_sdk/blob/auth2/src/java/us/kbase/templates/module_test_perl_client.vm.properties#L22 ?

2017-03-09 20:33 UTC, rsutormin commented on lib/DataFileUtil/DataFileUtilClient.pm
> +package DataFileUtil::DataFileUtilClient;
I don't see you using DFU anywhere in this PR. Is that right?

2017-03-09 21:59 UTC, msneddon commented on lib/KBaseReport/KBaseReportImpl.pm.bak-2017-03-06-15-59-41
> +package KBaseReport::KBaseReportImpl;
yeah, let me clean up those files- there are several bak files in there from before too.

2017-03-09 21:59 UTC, msneddon commented on test/KBaseReport_server_test.pl
>  my $auth_token = Bio::KBase::AuthToken->new(token => $token, ignore_authrc => 1);
hmm- it worked enough to save to CI workspace, but I'll switch to do use the better pattern.

2017-03-09 22:01 UTC, msneddon commented on lib/DataFileUtil/DataFileUtilClient.pm
> +package DataFileUtil::DataFileUtilClient;
Right- I was going to switch, but it seemed to work without doing that.  That will be round 2.

2017-03-10 21:15 UTC, rsutormin commented
@msneddon: PR looks good to me now. Let's merge it?

2017-03-10 21:19 UTC, merged